name: CI/CD Pipeline to deploy in Embassy Cloud EBI Openstack platform

on:
  push:
    branches:
      - pride
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  USERNAME: ${{ secrets.GHCR_USER }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker_build:
    environment: prod
    env:
      PORT: ${{ vars.PORT }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: create Dockerfile with environment variables
      run: envsubst < .Dockerfile > Dockerfile

    - name: Print Dockerfile
      run: cat Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ vars.API_GITHUB_REPOSITORY }}:latest
          ghcr.io/${{ vars.API_GITHUB_REPOSITORY }}:${{ env.IMAGE_TAG }}
